-- ============================================================================
-- KIA Skin Care - Rollback for Focused Launch Helper Restore Patch
-- Date: 2026-07-14
--
-- Scope:
--   Reverses only supabase/PATCH_RESTORE_LAUNCH_HELPERS_2026_07_14.sql.
--   It does not delete data, reset Auth users, remove generated IDs, or drop
--   ID sequences because live rows may depend on values generated by the patch.
-- ============================================================================

BEGIN;

-- ----------------------------------------------------------------------------
-- 1. Remove patch RLS policies.
-- ----------------------------------------------------------------------------
DROP POLICY IF EXISTS "profiles_select_own_or_admin" ON public.profiles;
DROP POLICY IF EXISTS "profiles_update_own_or_admin" ON public.profiles;
DROP POLICY IF EXISTS "profiles_insert_admin" ON public.profiles;
DROP POLICY IF EXISTS "profiles_read_own" ON public.profiles;

DROP POLICY IF EXISTS "contact_settings_admin_all" ON public.contact_settings;
DROP POLICY IF EXISTS public_read_contact_settings ON public.contact_settings;

DROP POLICY IF EXISTS "partners_admin_read_all" ON public.partners;
DROP POLICY IF EXISTS "partners_admin_update_limited" ON public.partners;

DROP POLICY IF EXISTS "memberships_admin_read_all" ON public.memberships;
DROP POLICY IF EXISTS "memberships_admin_write" ON public.memberships;

DROP POLICY IF EXISTS "bookings_admin_read_all" ON public.bookings;
DROP POLICY IF EXISTS "bookings_admin_write" ON public.bookings;

-- ----------------------------------------------------------------------------
-- 2. Restore the focused pre-patch policies shown by the live verification CSV.
-- ----------------------------------------------------------------------------
CREATE POLICY "profiles_read_own"
ON public.profiles
FOR SELECT
USING (auth.uid() = id);

CREATE POLICY public_read_contact_settings
ON public.contact_settings
FOR SELECT
USING (true);

CREATE POLICY "partners_admin_read_all"
ON public.partners
FOR SELECT
USING (
  EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE profiles.id = auth.uid()
      AND profiles.role = ANY (ARRAY['admin'::public.user_role, 'staff'::public.user_role])
  )
);

CREATE POLICY "partners_admin_update_limited"
ON public.partners
FOR UPDATE
USING (
  EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE profiles.id = auth.uid()
      AND profiles.role = 'admin'::public.user_role
  )
);

CREATE POLICY "memberships_admin_read_all"
ON public.memberships
FOR SELECT
USING (
  EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE profiles.id = auth.uid()
      AND profiles.role = ANY (ARRAY['admin'::public.user_role, 'staff'::public.user_role])
  )
);

CREATE POLICY "memberships_admin_write"
ON public.memberships
FOR ALL
USING (
  EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE profiles.id = auth.uid()
      AND profiles.role = ANY (ARRAY['admin'::public.user_role, 'staff'::public.user_role])
  )
);

CREATE POLICY "bookings_admin_read_all"
ON public.bookings
FOR SELECT
USING (
  EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE profiles.id = auth.uid()
      AND profiles.role = ANY (ARRAY['admin'::public.user_role, 'staff'::public.user_role])
  )
);

CREATE POLICY "bookings_admin_write"
ON public.bookings
FOR ALL
USING (
  EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE profiles.id = auth.uid()
      AND profiles.role = ANY (ARRAY['admin'::public.user_role, 'staff'::public.user_role])
  )
);

-- ----------------------------------------------------------------------------
-- 3. Remove patch triggers.
-- ----------------------------------------------------------------------------
DROP TRIGGER IF EXISTS trg_kia_assign_membership_id ON public.memberships;
DROP TRIGGER IF EXISTS trg_kia_assign_booking_ids ON public.bookings;
DROP TRIGGER IF EXISTS trg_kia_assign_partner_code_on_activation ON public.partners;
DROP TRIGGER IF EXISTS trg_kia_assign_referral_tree_transaction_id ON public.referral_tree;
DROP TRIGGER IF EXISTS trg_kia_assign_commission_referral_transaction_id ON public.commissions;

-- ----------------------------------------------------------------------------
-- 4. Remove patch functions. Sequences are intentionally preserved.
-- ----------------------------------------------------------------------------
DROP FUNCTION IF EXISTS public.kia_approve_paid_membership(uuid);
DROP FUNCTION IF EXISTS public.kia_lookup_referrer(text);
DROP FUNCTION IF EXISTS public.kia_assign_referral_transaction_id();
DROP FUNCTION IF EXISTS public.kia_assign_partner_code_on_activation();
DROP FUNCTION IF EXISTS public.kia_assign_booking_ids();
DROP FUNCTION IF EXISTS public.kia_assign_membership_id();
DROP FUNCTION IF EXISTS public.kia_next_referral_transaction_id();
DROP FUNCTION IF EXISTS public.kia_next_treatment_order_id();
DROP FUNCTION IF EXISTS public.kia_next_booking_id();
DROP FUNCTION IF EXISTS public.kia_next_membership_id();
DROP FUNCTION IF EXISTS public.kia_next_partner_code();
DROP FUNCTION IF EXISTS public.kia_is_admin(uuid);

COMMIT;

-- ============================================================================
-- Verification queries
-- ============================================================================
-- SELECT n.nspname AS schema, p.proname, pg_get_function_identity_arguments(p.oid) AS args
-- FROM pg_proc p
-- JOIN pg_namespace n ON n.oid = p.pronamespace
-- WHERE n.nspname = 'public' AND p.proname LIKE 'kia_%'
-- ORDER BY p.proname;
--
-- SELECT event_object_table, trigger_name
-- FROM information_schema.triggers
-- WHERE trigger_schema = 'public' AND trigger_name LIKE 'trg_kia_%'
-- ORDER BY event_object_table, trigger_name;
--
-- SELECT schemaname, tablename, policyname, cmd, qual, with_check
-- FROM pg_policies
-- WHERE schemaname = 'public'
--   AND tablename IN ('profiles','contact_settings','partners','memberships','bookings')
-- ORDER BY tablename, policyname;
