export const treatmentKitCatalog = [
  {
    slug: "advance-kit",
    title: "Advance Kit",
    kitName: "Advance Kit",
    price: 18000,
    priceLabel: "₹18,000",
    unit: "complete kit",
    type: "home_kit",
    treatmentType: "home-kit",
    tagline: "Advanced Home Kit",
    subtitle: "Advanced Home Kit",
    description:
      "Advanced skincare kit designed for enhanced glow and visible skin improvement.",
    overview:
      "Advanced skincare kit designed for enhanced glow and visible skin improvement.",
    benefits: [
      "Advanced skin repair",
      "Pigmentation support",
      "Premium guided home care",
      "Visible radiance",
    ],
    process: [],
    whoFor: ["Advanced home-care clients", "Pigmentation and repair focused users"],
    safety: "Doctor-guided and patch-tested for responsible home use.",
    faqs: [],
    duration: "4-6 weeks",
    sessions: "Complete kit program",
    badge: "Premium Kit",
    icon: "award",
    tone: "primaryDark",
    image:
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=1400&q=80",
    imageAlt: "Advance skincare kit",
    note: "Includes premium home-care kit delivery.",
    ctaText: "Book Advance Kit",
    featured: true,
    requiresSlots: false,
    availableCities: ["All India"],
  },
  {
    slug: "japanese-kit",
    title: "Japanese Kit",
    kitName: "Japanese Kit",
    price: 22000,
    priceLabel: "₹22,000",
    unit: "complete kit",
    type: "home_kit",
    treatmentType: "home-kit",
    tagline: "Japanese Ritual Kit",
    subtitle: "Japanese Ritual Kit",
    description:
      "Premium Japanese-inspired skincare kit for refined texture and smooth skin appearance.",
    overview:
      "Premium Japanese-inspired skincare kit for refined texture and smooth skin appearance.",
    benefits: [
      "Texture refinement",
      "Calm clear skin",
      "Balanced glow",
      "Gentle home ritual",
    ],
    process: [],
    whoFor: ["Sensitive skin", "Texture refinement", "Refined glow seekers"],
    safety: "Gentle, guided, and suitable for premium home-care routines.",
    faqs: [],
    duration: "4-6 weeks",
    sessions: "Complete kit program",
    badge: "Japanese Care",
    icon: "sparkle",
    tone: "light",
    image:
      "https://images.unsplash.com/photo-1596755389378-c31d21fd1273?auto=format&fit=crop&w=1400&q=80",
    imageAlt: "Japanese skincare kit",
    note: "Includes Japanese-inspired skincare kit.",
    ctaText: "Book Japanese Kit",
    featured: false,
    requiresSlots: false,
    availableCities: ["All India"],
  },
  {
    slug: "korean-glass-kit",
    title: "Korean Glass Kit",
    kitName: "Korean Glass Kit",
    price: 15000,
    priceLabel: "₹15,000",
    unit: "complete kit",
    type: "home_kit",
    treatmentType: "home-kit",
    tagline: "Glass Glow Home Kit",
    subtitle: "Glass Glow Home Kit",
    description:
      "Kit-based Korean glass skin care option for a fresh, radiant look.",
    overview:
      "Kit-based Korean glass skin care option for a fresh, radiant look.",
    benefits: [
      "Glass-skin glow",
      "Hydration support",
      "Dewy finish",
      "K-beauty inspired care",
    ],
    process: [],
    whoFor: ["Dull skin", "Hydration seekers", "K-beauty glow lovers"],
    safety: "Patch-tested, guided home care for visible glow.",
    faqs: [],
    duration: "4-6 weeks",
    sessions: "Complete kit program",
    badge: "Glass Kit",
    icon: "sparkle",
    tone: "accent",
    image:
      "https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?auto=format&fit=crop&w=1400&q=80",
    imageAlt: "Korean glass skincare kit",
    note: "Includes Korean glass glow kit.",
    ctaText: "Book Korean Glass Kit",
    featured: true,
    requiresSlots: false,
    availableCities: ["All India"],
  },
  {
    slug: "basic-kit",
    title: "Basic Kit",
    kitName: "Basic Kit",
    price: 14000,
    priceLabel: "₹14,000",
    unit: "complete kit",
    type: "home_kit",
    treatmentType: "home-kit",
    tagline: "Essential Skin Kit",
    subtitle: "Essential Skin Kit",
    description:
      "Essential skincare kit for regular care and beginner-level treatment support.",
    overview:
      "Essential skincare kit for regular care and beginner-level treatment support.",
    benefits: [
      "Beginner friendly",
      "Glow maintenance",
      "Hydration and cleansing",
      "All-skin support",
    ],
    process: [],
    whoFor: ["First-time skincare clients", "Maintenance care", "All skin types"],
    safety: "Gentle, simple, and designed for guided everyday use.",
    faqs: [],
    duration: "4-6 weeks",
    sessions: "Complete kit program",
    badge: "Essential",
    icon: "droplet",
    tone: "primary",
    image:
      "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=1400&q=80",
    imageAlt: "Basic skincare kit",
    note: "Includes essential skincare kit.",
    ctaText: "Book Basic Kit",
    featured: false,
    requiresSlots: false,
    availableCities: ["All India"],
  },
  {
    slug: "korean-glass-treatment",
    title: "Korean Glass Treatment Campaign",
    kitName: "Korean Glass Treatment Campaign",
    price: 25000,
    priceLabel: "₹25,000",
    unit: "per session",
    type: "campaign",
    treatmentType: "camp",
    tagline: "Premium Clinical Glow Experience",
    subtitle: "Premium Clinical Glow Experience",
    description:
      "Campaign/location-based premium Korean glass treatment. Our team will contact you on WhatsApp with campaign date and location details.",
    overview:
      "Campaign/location-based premium Korean glass treatment. Our team will contact you on WhatsApp with campaign date and location details.",
    benefits: [
      "Deep hydration glow",
      "Glass skin finish",
      "Skin texture refinement",
      "Premium clinical care",
    ],
    process: [],
    whoFor: ["Pre-event glow seekers", "Dry or dull skin", "Premium clinical care clients"],
    safety: "Doctor-supervised and delivered in premium clinical settings.",
    faqs: [],
    duration: "75-90 min",
    sessions: "Event-based sessions",
    badge: "Premium",
    icon: "sparkle",
    tone: "accent",
    image:
      "https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?auto=format&fit=crop&w=1400&q=80",
    imageAlt: "Korean Glass Treatment Campaign",
    note: "Our team will contact you on WhatsApp for campaign location and schedule.",
    ctaText: "Enquire Now",
    featured: true,
    requiresSlots: true,
    availableCities: ["Mumbai", "Delhi", "Bangalore", "Ahmedabad"],
  },
] as const;

export const treatmentKitSlugs = treatmentKitCatalog.map((treatment) => treatment.slug);

export const bookingTreatmentSlugAliases: Record<string, string> = {
  "advance-kit": "advanced-skin-treatment",
  "japanese-kit": "japanese-skin-treatment",
  "korean-glass-kit": "korean-glass-skin",
  "basic-kit": "basic-skin-treatment",
  "korean-glass-treatment": "korean-glass-skin",
};

export const bookingTreatmentOrder = [
  "advanced-skin-treatment",
  "japanese-skin-treatment",
  "korean-glass-skin",
  "skin-lightening",
  "basic-skin-treatment",
  ...treatmentKitSlugs,
] as const;

export function normalizeBookingTreatmentSlug(slug?: string | null) {
  const cleanSlug = String(slug || "").trim();
  return bookingTreatmentSlugAliases[cleanSlug] || cleanSlug;
}
